repository:
  topics: metrics, prometheus, prometheus-client
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  allow_auto_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: false
  enable_vulnerability_alerts: true

labels:
  - name: dependencies
    color: '#0052cc'
    description: Dependencies & Renovate bot

  - name: bug
    color: '#d73a4a'
    description: Unexpected problem or unintended behavior

  - name: documentation
    color: '#0075ca'
    description: Improvements or additions to documentation

  - name: duplicate
    color: '#cfd3d7'
    description: Duplicate

  - name: enhancement
    color: '#a2eeef'
    description: Feature request

  - name: good first issue
    color: '#7057ff'
    description: Good issue for first-time contributors

  - name: help wanted
    color: '#008672'
    description: Wants help

  - name: invalid
    color: '#e4e669'
    description: Not relevant

  - name: question
    color: '#d876e3'
    description: Needs more information

  - name: wontfix
    color: '#ffffff'
    description: Work won't continue

  - name: vulnerability
    color: '#d1260f'
    description: Security vulnerability

collaborators:
  - username: phnx47-bot
    # Direct push to 'main' branch. Try integrate automerge like this https://github.com/marketplace/actions/enable-github-automerge
    permission: admin
teams:
  - name: devs
    permission: maintain
