repository:
  topics: metrics, prometheus, prometheus-client
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  allow_auto_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: false
  enable_vulnerability_alerts: true

collaborators:
  - username: phnx47-bot
    permission: admin # direct push to main branch. Try integrate automerge like this https://github.com/marketplace/actions/enable-github-automerge
teams:
  - name: devs
    permission: maintain
