group:
  - files:
      - source: .github/
        dest: .github/
        deleteOrphaned: true
        exclude: |
          sync.yml
          workflows/sync-files.yml
      - source: stylecop.json
        dest: stylecop.json
      - source: .editorconfig
        dest: .editorconfig
      - source: .gitattributes
        dest: .gitattributes
      - source: .gitignore
        dest: .gitignore
      - source: Directory.Build.props
        dest: Directory.Build.props
      - source: LICENSE
        dest: LICENSE
      - source: icon.png
        dest: icon.png
      - source: .ruleset
        dest: .ruleset
    repos: |
      prom-client-net/prom-client
      prom-client-net/prom-client-dependencyinjection
      prom-client-net/prom-client-healthchecks
      prom-client-net/prom-client-httprequestdurations
      prom-client-net/prom-client-aspnetcore
      prom-client-net/prom-client-metricpusher
      prom-client-net/prom-client-metricserver
